# Generated by Django 4.0.1 on 2022-02-05 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cita', models.TextField()),
                ('historia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sinopsis', models.TextField()),
                ('paginas', models.IntegerField()),
                ('idioma', models.CharField(max_length=50)),
                ('fecha_estreno', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.editorial')),
            ],
        ),
    ]
