# Generated by Django 4.0.1 on 2022-02-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagenLibro',
            field=models.ImageField(null=True, upload_to='libros'),
        ),
    ]
