# Generated by Django 4.0.1 on 2022-03-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_libro_imagenlibro'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagenAutor',
            field=models.ImageField(null=True, upload_to='libros'),
        ),
    ]
