# Generated by Django 4.0.1 on 2022-04-13 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_autor_imagenautor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGenero', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='nombreGenero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.genero'),
            preserve_default=False,
        ),
    ]
