# Generated by Django 4.0.1 on 2022-04-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_genero_libro_nombregenero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='nombreGenero',
            new_name='genero',
        ),
    ]
