# Generated by Django 4.0.1 on 2022-04-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_nombregenero_libro_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='nombreGenero',
            new_name='nombre',
        ),
    ]
