# Generated by Django 4.0.1 on 2022-04-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_nombregenero_genero_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='nombre',
            new_name='nombre1',
        ),
    ]
