# Generated by Django 4.0.1 on 2022-04-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_nombre_genero_nombre1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='nombre1',
            new_name='nombre',
        ),
    ]
