# Generated by Django 4.0.1 on 2022-04-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_nombre1_genero_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='nombre2',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genero',
            name='nombre3',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
