# Generated by Django 4.0.1 on 2022-04-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_genero_nombre2_genero_nombre3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='nombre2',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='nombre3',
        ),
    ]
