# Generated by Django 4.0.1 on 2022-04-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_genero_nombre2_remove_genero_nombre3'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroSecundario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroTerciario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Genero',
            new_name='GeneroPrimario',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='genero',
            new_name='generoPrimario',
        ),
        migrations.AddField(
            model_name='libro',
            name='generoSecundario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.generosecundario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='generoTerciario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.generoterciario'),
            preserve_default=False,
        ),
    ]
